name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      run: |
        npm install
        npm run lint
        npm run deployGHPages
